Repository dsccommunity/DnsServerDsc, pull requests merged in 2021-05, with the labels that each got.

#256 DnsRecordPtr: IPv6 hot fix
  CHANGELOG.md
  source/Classes/002.DnsRecordPtr.ps1
  tests/Unit/Classes/DnsRecordPtr.v6.tests.ps1
Labels: waiting for code fix

#258 DnsServerDsSetting: New Resource to Manage AD DNS settings
  CHANGELOG.md
  source/Classes/001.ResourceBase.ps1
  source/Classes/003.DnsServerDsSetting.ps1
  source/Examples/Resources/DnsServerDsSetting/1-DnsServerDsSetting_DirectoryPartitionAutoEnlistInterval_Config.ps1
  source/Examples/Resources/DnsServerDsSetting/2-DnsServerDsSetting_LazyUpdateInterval_Config.ps1
  source/Examples/Resources/DnsServerDsSetting/3-DnsServerDsSetting_MinimumBackgroundLoadThreads_Config.ps1
  source/Examples/Resources/DnsServerDsSetting/4-DnsServerDsSetting_PollingInterval_Config.ps1
  source/Examples/Resources/DnsServerDsSetting/5-DnsServerDsSetting_RemoteReplicationDelay_Config.ps1
  source/Examples/Resources/DnsServerDsSetting/6-DnsServerDsSetting_TombstoneInterval_Config.ps1
  source/Examples/Resources/DnsServerDsSetting/7-DnsServerDsSetting_All_Config.ps1
  source/en-US/DnsServerDsSetting.strings.psd1
  tests/Integration/Classes/DnsServerDsSetting.Integration.Tests.ps1
  tests/Integration/Classes/DnsServerDsSetting.config.ps1
  tests/Unit/Classes/DnsServerDsSetting.Tests.ps1
Labels: needs review

#257 DnsServerSetting: Refactor the resource to use cmdlet *-DnsServerSetting
  CHANGELOG.md
  debug.ps1
  source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1
  source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.schema.mof
  source/DSCResources/DSC_DnsServerSetting/README.md
  source/DSCResources/DSC_DnsServerSetting/en-US/DSC_DnsServerSetting.strings.psd1
  source/DSCResources/DSC_DnsServerSettingLegacy/DSC_DnsServerSettingLegacy.psm1
  source/DSCResources/DSC_DnsServerSettingLegacy/DSC_DnsServerSettingLegacy.schema.mof
  source/DSCResources/DSC_DnsServerSettingLegacy/README.md
  source/DSCResources/DSC_DnsServerSettingLegacy/en-US/DSC_DnsServerSettingLegacy.strings.psd1
  source/Examples/Resources/DnsServerSetting/1-DnsServerSetting_CurrentNode_Config.ps1
  source/Examples/Resources/DnsServerSetting/2-DnsServerSetting_RemoteNode_Config.ps1
  source/Examples/Resources/DnsServerSettingLegacy/1-DnsServerSettingLegacy_CurrentNode_Config.ps1
  source/Examples/Resources/DnsServerSettingLegacy/2-DnsServerSettingLegacy_RemoteNode_Config.ps1
  tests/Integration/DSC_DnsServerSetting.Integration.Tests.ps1
  tests/Integration/DSC_DnsServerSetting.config.ps1
  tests/Integration/DSC_DnsServerSettingLegacy.Integration.Tests.ps1
  tests/Integration/DSC_DnsServerSettingLegacy.config.ps1
  tests/Unit/DSC_DnsServerSetting.Tests.ps1
  tests/Unit/DSC_DnsServerSettingLegacy.Tests.ps1
Labels: ready for merge
