Repository dsccommunity/DnsServerDsc, pull requests merged in 2021-03, with the labels that each got.

#201 BREAKING CHANGE: DnsRecordSrv/DnsRecordSrvScoped: Re-implemented as class-based resource
  CHANGELOG.md
  source/Classes/001.DnsRecordBase.ps1
  source/Classes/002.DnsRecordSrv.ps1
  source/Classes/003.DnsRecordSrvScoped.ps1
  source/DSCResources/MSFT_xDnsRecordMx/MSFT_xDnsRecordMx.psm1
  source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.psm1
  source/DSCResources/MSFT_xDnsRecordSrv/MSFT_xDnsRecordSrv.schema.mof
  source/DSCResources/MSFT_xDnsRecordSrv/README.md
  source/DSCResources/MSFT_xDnsRecordSrv/en-US/MSFT_xDnsRecordSrv.strings.psd1
  source/DSCResources/MSFT_xDnsServerConditionalForwarder/MSFT_xDnsServerConditionalForwarder.psm1
  source/DSCResources/MSFT_xDnsServerDiagnostics/MSFT_xDnsServerDiagnostics.psm1
  source/DSCResources/MSFT_xDnsServerForwarder/MSFT_xDnsServerForwarder.psm1
  source/DSCResources/MSFT_xDnsServerSecondaryZone/MSFT_xDnsServerSecondaryZone.psm1
  source/DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.psm1
  source/DSCResources/MSFT_xDnsServerZoneTransfer/MSFT_xDnsServerZoneTransfer.psm1
  source/Enum/1.Ensure.ps1
  source/Examples/Resources/DnsRecordSrv/1-DnsRecordSrv_config.ps1
  source/Examples/Resources/DnsRecordSrv/2-DnsRecordSrv_full_config.ps1
  source/Examples/Resources/DnsRecordSrv/3-DnsRecordSrv_Remove_config.ps1
  source/Examples/Resources/DnsRecordSrvScoped/1-DnsRecordSrvScoped_config.ps1
  source/Examples/Resources/DnsRecordSrvScoped/2-DnsRecordSrvScoped_full_config.ps1
  source/Examples/Resources/DnsRecordSrvScoped/3-DnsRecordSrvScoped_Remove_config.ps1
  source/Private/ConvertTo-HashtableFromObject.ps1
  source/en-US/DnsRecordBase.strings.psd1
  source/en-US/DnsRecordSrv.strings.psd1
  source/en-US/DnsRecordSrvScoped.strings.psd1
  source/en-US/xDnsServer.strings.psd1
  source/xDnsServer.psd1
  source/xDnsServer.psm1
  tests/Integration/Classes/DnsRecordSrv.config.ps1
  tests/Integration/Classes/DnsRecordSrv.integration.tests.ps1
  tests/Integration/Classes/DnsRecordSrvScoped.config.ps1
  tests/Integration/Classes/DnsRecordSrvScoped.integration.tests.ps1
  tests/Integration/MSFT_xDnsRecordSrv.config.ps1
  tests/Unit/Classes/DnsRecordBase.tests.ps1
  tests/Unit/Classes/DnsRecordSrv.tests.ps1
  tests/Unit/Classes/DnsRecordSrvScoped.tests.ps1
  tests/Unit/MSFT_xDnsRecordSrv.Tests.ps1
  tests/Unit/Private/ConvertTo-HashtableFromObject.tests.ps1
  tests/Unit/Stubs/DnsServer.psm1
Labels: needs review

#202 BREAKING CHANGE: xDnServerSetting: Remove properties
  CHANGELOG.md
  source/DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.psm1
  source/DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof
  tests/Integration/MSFT_xDnsServerSetting.Integration.Tests.ps1
  tests/Integration/MSFT_xDnsServerSetting.config.ps1
  tests/Unit/MSFT_xDnsServerSetting.Tests.ps1
Labels: breaking change, ready for merge

#206 BREAKING CHANGE: DnsRecordA/DnsRecordAScoped: Re-implemented as class-based resources
  CHANGELOG.md
  source/Classes/002.DnsRecordA.ps1
  source/Classes/003.DnsRecordAScoped.ps1
  source/Examples/Resources/DnsRecordA/1-DnsRecordA_Mandatory_config.ps1
  source/Examples/Resources/DnsRecordA/2-DnsRecordA_Full_config.ps1
  source/Examples/Resources/DnsRecordA/3-DnsRecordA_Remove_config.ps1
  source/Examples/Resources/DnsRecordAScoped/1-DnsRecordAScoped_Mandatory_config.ps1
  source/Examples/Resources/DnsRecordAScoped/2-DnsRecordAScoped_Full_config.ps1
  source/Examples/Resources/DnsRecordAScoped/3-DnsRecordAScoped_Remove_config.ps1
  source/en-US/DnsRecordA.strings.psd1
  source/en-US/DnsRecordAScoped.strings.psd1
  tests/Integration/Classes/DnsRecordA.config.ps1
  tests/Integration/Classes/DnsRecordA.integration.tests.ps1
  tests/Integration/Classes/DnsRecordAScoped.config.ps1
  tests/Integration/Classes/DnsRecordAScoped.integration.tests.ps1
  tests/Unit/Classes/DnsRecordA.tests.ps1
  tests/Unit/Classes/DnsRecordAScoped.tests.ps1
  tests/Unit/MockObjects/ARecordInstance.xml
Labels: needs review

#207 xDnsServer: Update pipeline to use new deploy task
  CHANGELOG.md
  RequiredModules.psd1
  build.yaml
Labels: ready for merge

#210 DnsRecordCname/DnsRecordCnameScoped: Re-implemented as class-based resources
  CHANGELOG.md
  RequiredModules.psd1
  source/Classes/002.DnsRecordCname.ps1
  source/Classes/003.DnsRecordCnameScoped.ps1
  source/Examples/Resources/DnsRecordCNAME/1-DnsRecordCname_Mandatory_config.ps1
  source/Examples/Resources/DnsRecordCNAME/2-DnsRecordCname_Full_config.ps1
  source/Examples/Resources/DnsRecordCNAME/3-DnsRecordCname_Remove_config.ps1
  source/Examples/Resources/DnsRecordCNAMEScoped/1-DnsRecordCnameScoped_Mandatory_config.ps1
  source/Examples/Resources/DnsRecordCNAMEScoped/2-DnsRecordCnameScoped_Full_config.ps1
  source/Examples/Resources/DnsRecordCNAMEScoped/3-DnsRecordCnameScoped_Remove_config.ps1
  source/en-US/DnsRecordCname.strings.psd1
  source/en-US/DnsRecordCnameScoped.strings.psd1
  tests/Integration/Classes/DnsRecordCname.config.ps1
  tests/Integration/Classes/DnsRecordCname.integration.tests.ps1
  tests/Integration/Classes/DnsRecordCnameScoped.config.ps1
  tests/Integration/Classes/DnsRecordCnameScoped.integration.tests.ps1
  tests/Unit/Classes/DnsRecordCname.tests.ps1
  tests/Unit/Classes/DnsRecordCnameScoped.tests.ps1
  tests/Unit/MockObjects/CnameRecordInstance.xml
Labels: needs review

#212 xDnsServer: Revert back to using latest Sampler
  CHANGELOG.md
  RequiredModules.psd1
Labels: needs review

#214 DnsServerScavenging: Add new resource
  CHANGELOG.md
  build.yaml
  source/Classes/001.ResourceBase.ps1
  source/Classes/001.ResourcePropertiesBase.ps1
  source/Classes/002.DnsRecordBase.ps1
  source/Classes/003.DnsRecordA.ps1
  source/Classes/003.DnsRecordSrv.ps1
  source/Classes/003.DnsServerScavenging.ps1
  source/Classes/004.DnsRecordAScoped.ps1
  source/Classes/004.DnsRecordSrvScoped.ps1
  source/Examples/Resources/DnsServerScavenging/1-EnableAndChangeScavengingIntervals_Config.ps1
  source/Examples/Resources/DnsServerScavenging/2-EnableScavenging_Config.ps1
  source/Examples/Resources/DnsServerScavenging/3-ChangeScavengingIntervals_Config.ps1
  source/Examples/Resources/DnsServerScavenging/4-DisableScavenging_Config.ps1
  source/Private/ConvertTo-TimeSpan.ps1
  source/en-US/DnsRecordBase.strings.psd1
  source/en-US/DnsServerScavenging.strings.psd1
  source/en-US/ResourcePropertiesBase.strings.psd1
  source/prefix.ps1
  tests/Integration/Classes/DnsServerScavenging.Integration.Tests.ps1
  tests/Integration/Classes/DnsServerScavenging.config.ps1
  tests/Unit/Classes/DnsServerScavenging.Tests.ps1
  tests/Unit/Private/ConvertTo-TimeSpan.Tests.ps1
Labels: needs review

#213 DnsRecordPtr: Re-implemented as a class-based resource with IPv6 support.
  CHANGELOG.md
  source/Classes/002.DnsRecordPtr.ps1
  source/Examples/Resources/DnsRecordPtr/1-DnsRecordPtr_Mandatory_config.ps1
  source/Examples/Resources/DnsRecordPtr/2-DnsRecordPtr_Full_config.ps1
  source/Examples/Resources/DnsRecordPtr/3-DnsRecordPtr_Remove_config.ps1
  source/Examples/Resources/DnsRecordPtr/4-DnsRecordPtr_Mandatory_v6_config.ps1
  source/Examples/Resources/DnsRecordPtr/5-DnsRecordPtr_Full_v6_config.ps1
  source/Examples/Resources/DnsRecordPtr/6-DnsRecordPtr_Remove_v6_config.ps1
  source/en-US/DnsRecordPtr.strings.psd1
  tests/Integration/Classes/DnsRecordPtr.config.ps1
  tests/Integration/Classes/DnsRecordPtr.integration.tests.ps1
  tests/Integration/Classes/DnsRecordPtr.v6.config.ps1
  tests/Integration/Classes/DnsRecordPtr.v6.integration.tests.ps1
  tests/Unit/Classes/DnsRecordPtr.tests.ps1
  tests/Unit/Classes/DnsRecordPtr.v6.tests.ps1
  tests/Unit/MockObjects/PtrRecordInstance.xml
  tests/Unit/MockObjects/PtrV6RecordInstance.xml
Labels: ready for merge

#217 DnsRecordAaaa: Implemented as a class-based resource
  CHANGELOG.md
  source/Classes/003.DnsRecordAaaa.ps1
  source/Classes/004.DnsRecordAaaaScoped.ps1
  source/Examples/Resources/DnsRecordAaaa/1-DnsRecordAaaa_Mandatory_config.ps1
  source/Examples/Resources/DnsRecordAaaa/2-DnsRecordAaaa_Full_config.ps1
  source/Examples/Resources/DnsRecordAaaa/3-DnsRecordAaaa_Remove_config.ps1
  source/Examples/Resources/DnsRecordAaaaScoped/1-DnsRecordAaaaScoped_Mandatory_config.ps1
  source/Examples/Resources/DnsRecordAaaaScoped/2-DnsRecordAaaaScoped_Full_config.ps1
  source/Examples/Resources/DnsRecordAaaaScoped/3-DnsRecordAaaaScoped_Remove_config.ps1
  source/en-US/DnsRecordAaaa.strings.psd1
  source/en-US/DnsRecordAaaaScoped.strings.psd1
  tests/Integration/Classes/DnsRecordAaaa.config.ps1
  tests/Integration/Classes/DnsRecordAaaa.integration.tests.ps1
  tests/Integration/Classes/DnsRecordAaaaScoped.config.ps1
  tests/Integration/Classes/DnsRecordAaaaScoped.integration.tests.ps1
  tests/Unit/Classes/DnsRecordAaaa.tests.ps1
  tests/Unit/Classes/DnsRecordAaaaScoped.tests.ps1
  tests/Unit/MockObjects/AaaaRecordInstance.xml
Labels: ready for merge

#222 xDnsServer: Add deprecation messages to CHANGELOG.md
  CHANGELOG.md
Labels: needs review

#226 xDnsServer: Fix GitHub templates
  .github/ISSUE_TEMPLATE/Problem_with_resource.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: needs review

#223 xDnsServerForwarder: Added new properties `Timeout` and `EnableReordering`
  CHANGELOG.md
  source/DSCResources/MSFT_xDnsServerForwarder/MSFT_xDnsServerForwarder.psm1
  source/DSCResources/MSFT_xDnsServerForwarder/MSFT_xDnsServerForwarder.schema.mof
  source/DSCResources/MSFT_xDnsServerForwarder/README.md
  source/DSCResources/MSFT_xDnsServerForwarder/en-US/MSFT_xDnsServerForwarder.strings.psd1
  source/Examples/Resources/xDnsServerForwarder/4-xDnsServerForwarder_EnableReordering_Config.ps1
  source/Examples/Resources/xDnsServerForwarder/5-xDnsServerForwarder_DisableReordering_Config.ps1
  source/Examples/Resources/xDnsServerForwarder/6-xDnsServerForwarder_SetTimeout_Config.ps1
  tests/Integration/MSFT_xDnsServerForwarder.Integration.Tests.ps1
  tests/Integration/MSFT_xDnsServerForwarder.config.ps1
  tests/Unit/MSFT_xDnsServerForwarder.Tests.ps1
Labels: needs review

#219 BREAKING CHANGE: xDnsServerSetting: Remove properties
  CHANGELOG.md
  source/DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.psm1
  source/DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof
  source/Examples/Resources/xDnsServerSetting/1-xDnsServerSetting_CurrentNode_Config.ps1
  source/Examples/Resources/xDnsServerSetting/2-xDnsServerSetting_RemoteNode_Config.ps1
  tests/Integration/MSFT_xDnsServerSetting.Integration.Tests.ps1
  tests/Integration/MSFT_xDnsServerSetting.config.ps1
  tests/Unit/MSFT_xDnsServerSetting.Tests.ps1
Labels: needs review

#231 BREAKING CHANGE: xDnsServerSetting: Remove properties `Forwarders` and `ForwardingTimeout`
  CHANGELOG.md
  source/DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.psm1
  source/DSCResources/MSFT_xDnsServerSetting/MSFT_xDnsServerSetting.schema.mof
  source/Examples/Resources/xDnsServerSetting/1-xDnsServerSetting_CurrentNode_Config.ps1
  source/Examples/Resources/xDnsServerSetting/2-xDnsServerSetting_RemoteNode_Config.ps1
  tests/Integration/MSFT_xDnsServerSetting.Integration.Tests.ps1
  tests/Integration/MSFT_xDnsServerSetting.config.ps1
  tests/Unit/MSFT_xDnsServerSetting.Tests.ps1
Labels: needs review

#232 BREAKING CHANGE: xDnsServerMx: Remove resource
  CHANGELOG.md
  source/DSCResources/MSFT_xDnsRecordMx/MSFT_xDnsRecordMx.psm1
  source/DSCResources/MSFT_xDnsRecordMx/MSFT_xDnsRecordMx.schema.mof
  source/DSCResources/MSFT_xDnsRecordMx/README.md
  source/DSCResources/MSFT_xDnsRecordMx/en-US/MSFT_xDnsRecordMx.strings.psd1
  source/Examples/Resources/xDnsRecordMx/1-xDnsRecordMx_config.ps1
  source/Examples/Resources/xDnsRecordMx/2-xDnsRecordMx_Remove_config.ps1
  tests/Integration/MSFT_xDnsRecordMx.Integration.tests.ps1
  tests/Integration/MSFT_xDnsRecordMx.config.ps1
Labels: needs review

#233 BREAKING CHANGE: xDnsRecord: Remove resource
  CHANGELOG.md
  source/DSCResources/MSFT_xDnsRecord/MSFT_xDnsRecord.psm1
  source/DSCResources/MSFT_xDnsRecord/MSFT_xDnsRecord.schema.mof
  source/DSCResources/MSFT_xDnsRecord/README.md
  source/DSCResources/MSFT_xDnsRecord/en-US/MSFT_xDnsRecord.strings.psd1
  source/Examples/Resources/xDnsRecord/1-xDnsRecord_ARecord_config.ps1
  source/Examples/Resources/xDnsRecord/2-xDnsRecord_RoundRobin_config.ps1
  source/Examples/Resources/xDnsRecord/3-xDnsRecord_CName_config.ps1
  source/Examples/Resources/xDnsRecord/4-xDnsRecord_PTR_config.ps1
  source/Examples/Resources/xDnsRecord/5-xDnsRecord_ARecordRemove_config.ps1
  tests/Unit/MSFT_xDnsRecord.Tests.ps1
Labels: needs review

#234 DnsServerDsc: Fix stub Get-DnsServerResourceRecord
  CHANGELOG.md
  tests/Unit/Stubs/DnsServer.psm1
Labels: needs review

#240 DnsServerDsc Integration tests: Wait for LCM Idle
  CHANGELOG.md
  tests/Integration/Classes/DnsRecordA.integration.tests.ps1
  tests/Integration/Classes/DnsRecordAScoped.integration.tests.ps1
  tests/Integration/Classes/DnsRecordAaaa.integration.tests.ps1
  tests/Integration/Classes/DnsRecordAaaaScoped.integration.tests.ps1
  tests/Integration/Classes/DnsRecordCname.integration.tests.ps1
  tests/Integration/Classes/DnsRecordCnameScoped.integration.tests.ps1
  tests/Integration/Classes/DnsRecordMx.integration.tests.ps1
  tests/Integration/Classes/DnsRecordMxScoped.integration.tests.ps1
  tests/Integration/Classes/DnsRecordPtr.integration.tests.ps1
  tests/Integration/Classes/DnsRecordPtr.v6.integration.tests.ps1
  tests/Integration/Classes/DnsRecordSrv.integration.tests.ps1
  tests/Integration/Classes/DnsRecordSrvScoped.integration.tests.ps1
Labels: ready for merge

#243 BREAKING CHANGE: DnsServerSetting: Remove properties `EnableEDnsProbes` and `EDnsCacheTimeout`
  CHANGELOG.md
  source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1
  source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.schema.mof
  tests/Integration/DSC_DnsServerSetting.Integration.Tests.ps1
  tests/Integration/DSC_DnsServerSetting.config.ps1
  tests/Unit/DSC_DnsServerSetting.Tests.ps1
Labels: needs review

#244 BREAKING CHANGE: xDnsServerSetting: Remove properties `SecureResponses`, `MaxCacheTTL`, and `MaxNegativeCacheTTL`
  CHANGELOG.md
  source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.psm1
  source/DSCResources/DSC_DnsServerSetting/DSC_DnsServerSetting.schema.mof
  source/Examples/Resources/DnsServerSetting/1-DnsServerSetting_CurrentNode_Config.ps1
  source/Examples/Resources/DnsServerSetting/2-DnsServerSetting_RemoteNode_Config.ps1
  tests/Integration/DSC_DnsServerSetting.config.ps1
  tests/Unit/DSC_DnsServerSetting.Tests.ps1
Labels: needs review
